#!/bin/sh
# $Id: START_KS,v 1.3 2005/10/11 17:57:27 bew Exp $
# $Source: /nfs/cscbz/gdoi/gdoicvs/gdoi/samples/three-clients/START_KS,v $

../../src/gdoid -d -n -p848 -DA=99 -f/tmp/isakmpd2.fifo -cgdoi_ks.conf
