#!/bin/sh
# $Id: START_CLIENT3,v 1.3 2005/10/11 17:57:27 bew Exp $
# $Source: /nfs/cscbz/gdoi/gdoicvs/gdoi/samples/three-clients/START_CLIENT3,v $

../../src/gdoid -d -n -p848 -DA=99 -f/tmp/isakmpd.fifo -cgdoi_client3.conf
