#!/bin/sh
# $Id: START_CLIENT,v 1.3 2005/10/11 17:57:25 bew Exp $
# $Source: /nfs/cscbz/gdoi/gdoicvs/gdoi/samples/loopback/START_CLIENT,v $

../../src/gdoid -d -n -DA=59 -f/tmp/isakmpd.fifo -cgdoi_client.conf
