#!/bin/sh
# $Id: START_KS,v 1.4 2007/03/21 20:02:55 bew Exp $
# $Source: /nfs/cscbz/gdoi/gdoicvs/gdoi/samples/loopback/START_KS,v $

#
# Create a second loopback. The syntax varies per system. Uncomment the
# appropriate line below.
# For OS X, use the following line
# ifconfig lo0 127.0.0.2 alias
#
# For Linux, use the following line
# ifconfig lo:1 127.0.0.2 
#
# For BSD, use the following line
# ifconfig lo1 127.0.0.2 
#

../../src/gdoid -d -n -DA=59 -f/tmp/isakmpd2.fifo -cgdoi_ks.conf
